spring.application.name=courtbooking

# Default profile is dev.
# Local computer uses dev.
# AWS / production server should set SPRING_PROFILES_ACTIVE=prod.
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Default backend port
server.port=${SERVER_PORT:8080}

# Load local .env file
spring.config.import=optional:file:./.env[.properties]

stripe.secret-key=${STRIPE_SECRET_KEY:sk_test_not_configured}
app.frontend-url=${FRONTEND_URL:http://localhost:5173}

stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:whsec_not_configured}
