spring.application.name=courtbooking

# Default profile is dev.
# Local computer uses dev.
# AWS / production server should set SPRING_PROFILES_ACTIVE=prod.
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Default backend port
server.port=${SERVER_PORT:8080}